### ISSUE TITLE
radiola remains active in the "now playing" control

### ISSUE THREAD

**Issue by Mesandro** [SokoloffA/radiola#49] opened 2024-10-29 21:41 UTC
I use Radiola every day, but after installing a new software to manage the notch on my macbook I noticed something that I hadn't noticed before. In practice, Radiola even when it is paused (i.e. started and paused subsequently) remains active in all programs that manage audio playback. For example, even the mac os system manager in the menu bar (now playing control in sonoma/sequoia). For those who use different audio programs such as spotify music etc this can be a problem in some cases. In my case, the software I use to manage audio always recognizes Radiola as open, disturbing the use of other software. In fact, currently I am forced to completely exit the Radiola app when I am not using it. Is it possible to solve this problem with an option or a flag? In practice, Radiola should go to stop instead of paused (without exiting the software). I hope I have explained the issue well.

**Comment by SokoloffA** [comment] 2024-11-03 09:18
I'm not quite sure what the problem is. 

I looked at how other programs behave and I don't see any differences. I've been testing on macOS Sonoma 14.6.1.
1. I launch Coq and click Play in it. "Playing now" shows Coq. The multimedia keys toggle Coq. 
![Снимок экрана 2024-11-03 в 11 51 15](https://github.com/user-attachments/assets/18efe548-c12e-46b7-9f43-7183472754c7)
2. I stop playback in Coq. "Playing now" shows Coq. The multimedia keys toggle Coq.
![Снимок экрана 2024-11-03 в 11 51 41](https://github.com/user-attachments/assets/8a158b04-6476-4d12-b1f3-05508f72c016)
3. I turn on the playback in Radiola. "Playing now" shows Radiola. The multimedia keys toggle Radiola.
![Снимок экрана 2024-11-03 в 11 52 23](https://github.com/user-attachments/assets/bd443f6f-bb6e-4dd0-af46-72915b1981b9)
4. I stop playback in Radiola. "Playing now" shows Radiola. The multimedia keys toggle Radiola.
![Снимок экрана 2024-11-03 в 11 52 45](https://github.com/user-attachments/assets/5b3e47db-b948-4319-9aa5-e47ca6857f31)
5. When I ate play in the Coq window it becomes active in “Playing Now” and everything repeats from point 1.

--- 
As far as I understand macOs logic that “Playing Now” shows the last active application and binds the multimedia keys to it.

In the current version, I really sets the .interrupted status. 
[case .paused: MPNowPlayingInfoCenter.default().playbackState = .interrupted](
https://github.com/SokoloffA/radiola/blob/bda108c15323d3957b9bbae9e5fd60c3df9325a1/Radiola/MediaKeysController.swift#L44)
But I tried sending the .stopped status and saw no difference.

---

* Please clarify what “a new software to manage the notch on my macbook” means.
* Please describe how you test behavior.
* What behavior you expect. 
* If you know an opensource program that behaves the way you want, it would help me a lot.

**Comment by Mesandro** [comment] 2024-11-03 22:34
Hi, thanks for the answer in the meantime. I'll try to explain the issue to you as best I can. I noticed the behavior problem using a software available here on github called "[BoringNotch](https://github.com/TheBoredTeam/boring.notch?tab=readme-ov-file)". This software basically manages the play/pause of the various audio playback software from the macbook's notch instead of from the control center. The software works well with all playbacks, such as Music, Spotify, Safari etc. and in each of these software when I press "pause" the software recognizes that there is nothing more playing (in the control center instead the last software used remains as described by you) and disappears as it does not find anything active at that moment. The only software that has a different behavior among those I use is precisely Radiola. Basically once Radiola is used, even if paused, boringNotch recognizes this as if it were still playing audio. I don't know now if it could be a problem with the other software that recognizes Radiola in a "different" way when it is running, but basically the difference is that Radiola even when paused keeps this software active. I hope this helps, if you have any other questions I will try to answer them as best as I can. Thanks for your wonderful software!

**Comment by SokoloffA** [comment] 2024-11-04 19:11
If I understood correctly, you are saying that when the radio pauses, BoringNotch keeps counting down the seconds. 
I think this is a bug in BoringNotch, it behaves strangely for example:
* Cover art doesn't change when changing program
* The previous track duration is shown.
* I found a similar problem in Coq player.

For my part, I found a workaround. If the program not only changes status but also sends an empty track name, BoringNotch's behavior becomes more reasonable.

**Comment by Mesandro** [comment] 2024-11-04 21:25
Exactly. Unfortunately, I am not an expert and I noticed the anomaly only with Radiola and I thought to report it here, but it is probably as you say and I will report it to the BoringNotch team! Thank you very much

**Comment by SokoloffA** [comment] 2024-11-04 21:46
I haven't looked at the BoringNotch code, this is my guess. I think they don't look at statuses, but only metadata. Normal players like Music or Spotify have a full set of metadata, Artis, Track, track duration, current position in the track, cover art, etc. 
But Radiola doesn't know the duration of the track, doesn't have the cover art, etc. All the program has is the name of the radio station and the name of the Artist and the Song title in the form of the string “Artist - Title”.  The program sends only this to “Playing Now”. IMHO the rest of the metadata should be reset when the active program is changed.

**Comment by SokoloffA** [comment] 2024-12-19 15:40
Released in 8.0.0

**Closed by SokoloffA** 2024-12-19 15:40 UTC
Labels: done
