### ISSUE TITLE
Menu bar icon does not work with Bartender 5

### ISSUE THREAD

**Issue by gsportelli** [SokoloffA/radiola#42] opened 2024-09-08 15:40 UTC
When using Radiola 7.0.2 with Bartender 5.12 on MacOS 14.3.1, the icon on the menubar is unresponsive, and sometimes it shows a danger triangle like the one below:

<img width="402" alt="image" src="https://github.com/user-attachments/assets/0c23b2b0-5784-4365-b322-d607fe3daa65">

If I close Bartender, the icon works again.

The feedback from Bartender support was: "Occasionally, we'll hear of apps that have code that's meant to never show or never hide them from the menu bar although I can't say for certain that's what's happening here."

**Comment by SokoloffA** [comment] 2024-09-11 17:32
Unfortunately Apple doesn't provide an API to determine which mouse button is clicked in the menu bar. So I had to use some hacks, they don't seem to work with programs like Bartender. 

I'll install the trial version and try to fix the bug. 
Bartender is it from www.macbartender.com?
What does the yellow exclamation mark on the program icon mean?

**Comment by gsportelli** [comment] 2024-09-11 17:58
Yes, Bartender is that one. I don't know what the exclamation mark means. It is the first time I see it, maybe it is the Bartender app that overlays it.

If it helps, [Caffeine](https://github.com/domzilla/Caffeine) is another open-source app that detects right clicks and has no problems with Bartender.

**Comment by SokoloffA** [comment] 2024-09-11 21:06
Thanks so much for the Caffeine, I'll have a look at how they did it.

**Comment by SokoloffA** [comment] 2024-09-14 08:59
It's very strange. I downloaded Bartender 5.1.2 from their website. And I have everything working, no yellow triangle and work fine:
* left click
* right click
* middle mouse button click
* scroll wheel

Apple M1,
macOs Sonoma 14.6.1
Bartender 5.1.2
Radiola 7.0.2

I only see one difference, I have a slightly newer macOS. If you get a chance try upgrading the OS.

**Comment by gsportelli** [comment] 2024-09-14 14:23
I just upgraded MacOS to 14.6.1, but the problem persists. Sorry for not specifying that it was also working initially for me, but it suddenly stopped working.

**Comment by gsportelli** [comment] 2024-09-14 14:30
P.S. Have you tried using the option "Show menu bar items in a bar below the menu bar" (see below)?

<img width="570" alt="image" src="https://github.com/user-attachments/assets/6e8c58e0-538d-4ea5-bb8c-4079b9ac3647">

I've just found that if I deactivate this option the Radiola icon starts working again. Even though it is suboptimal, it can be used as a workaround.

**Comment by SokoloffA** [comment] 2024-09-14 14:36
It still works. Send me screenshots of your settings.

**Comment by gsportelli** [comment] 2024-09-14 14:52
![image](https://github.com/user-attachments/assets/8c6780c0-ce11-4a26-aa63-ea5ca18e5e91)

![image](https://github.com/user-attachments/assets/411536dd-26a4-4aea-948a-cb16ee5ea0e3)

![image](https://github.com/user-attachments/assets/ede9d70a-d870-48c2-b817-f8fb1ab788d5)

![image](https://github.com/user-attachments/assets/7e29ff81-393c-4f64-bbee-7e4950b5954b)

![image](https://github.com/user-attachments/assets/436c01fe-a552-47b5-bd4e-7c40c8c072ee)

![image](https://github.com/user-attachments/assets/463a9d00-7485-4edc-8175-007e1b7663dd)

**Comment by SokoloffA** [comment] 2024-09-15 18:50
I couldn't reproduce the problem. I wrote to Bartender support about the triangle, maybe that will clear things up.
By the way, if you close Bartender, does the triangle disappear?

**Comment by gsportelli** [comment] 2024-09-15 22:19
Yes, if I close Bartender the triangle disappears. Then if I open Bartender again, the triangle appears after I try to interact with the Radiola menu bar icon. I also wrote another email to Bartender support pointing to this issue on GitHub.

Here below is a screen record of the issue.

https://github.com/user-attachments/assets/5bfc612c-92cb-47a0-a3f9-e7c2a1176f41

**Comment by SokoloffA** [comment] 2024-09-21 10:18
I was able to reproduce the situation. I have fixed the problem, I hope.
I am posting a link to the test version of the program .
[Radiola-7.0.2-dev.dmg.zip](https://github.com/user-attachments/files/17083721/Radiola-7.0.2-dev.dmg.zip)

**Comment by gsportelli** [comment] 2024-09-21 13:45
With the new version, the triangle doesn't show up anymore, but the radio works only when the menu icon is visible. When bartender hides it, the music stops.

**Comment by SokoloffA** [comment] 2024-09-21 18:42
The previous version didn't work quite right. I am posting a new one.
The fixes are not related to playback stopping, but I don't understand why playback might stop.

I have a few questions.
* What does “music stops” mean?
  * the program pauses
  * the program turns on mute (a small letter M appears on the icon)
  * the program shows that it is playing, but there is no sound?
* There was an update to Bartender today, did you update?
* Send me screenshot of the “Controls” tab of the Radiola settings window. 

[Radiola-7.0.2-dev2.dmg.zip](https://github.com/user-attachments/files/17085436/Radiola-7.0.2-dev2.dmg.zip)

**Comment by gsportelli** [comment] 2024-09-22 15:04
I've now updated Bartender and with your 7.0.2-dev2 the problem seems solved. Thank you!

Regarding your questions:

> What does “music stops” mean?

With the previous version, when I say that the music stops I meant that the music was not audible whenever the icon was hidden because of Bartender operation.

> the program pauses
> the program turns on mute (a small letter M appears on the icon)
> the program shows that it is playing, but there is no sound?

I can't say if the program was paused or muted, because it all happened while the icon was hidden. When the icon reappeared, the music would resume without any other user interaction.

> There was an update to Bartender today, did you update?

My last message was before updating Bartender.

> Send me screenshot of the “Controls” tab of the Radiola settings window.

Here are the screenshots taken with 7.0.2-dev2. I haven't changed any settings.

<img width="678" alt="image" src="https://github.com/user-attachments/assets/ab663969-fdee-49bd-adb5-e7ecc2a33949">

<img width="678" alt="image" src="https://github.com/user-attachments/assets/2d604287-9ab6-4d48-b742-392794692977">

<img width="678" alt="image" src="https://github.com/user-attachments/assets/b3abab96-8db6-4936-aa61-7ed801b29767">

<img width="678" alt="image" src="https://github.com/user-attachments/assets/e4edb8ab-0c2e-45c3-90a9-c5ac2153eb86">

<img width="678" alt="image" src="https://github.com/user-attachments/assets/de5b9045-9774-4e42-8076-f13fed5f1def">

**Comment by SokoloffA** [comment] 2024-12-19 15:40
Released in 8.0.0

**Closed by SokoloffA** 2024-12-19 15:40 UTC
Labels: done
